#!/usr/bin/env python3
"""Generate an English presentation ER figure for the final report."""

from __future__ import annotations

from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas


OUTPUT = Path("docs/diagramas/er-english.pdf")

BOXES = [
    ("Users", "Authentication and identity", 2.0, 2.0),
    ("Roles", "RBAC catalog", 9.0, 2.0),
    ("Permissions", "Authorization rules", 16.0, 2.0),
    ("Books", "Bibliographic records", 2.0, 6.0),
    ("Authors", "Author catalog", 9.0, 6.0),
    ("Categories", "Subject catalog", 16.0, 6.0),
    ("Publishers", "Publisher catalog", 23.0, 6.0),
    ("Loans", "Book lending lifecycle", 2.0, 10.0),
    ("Reservations", "Hold requests", 9.0, 10.0),
    ("Fines", "Penalties and payments", 16.0, 10.0),
    ("Notifications", "In-app alerts", 23.0, 10.0),
    ("Acquisition Suggestions", "Reader requests", 2.0, 14.0),
    ("Backups", "Operational backups", 9.0, 14.0),
    ("Audit Log", "Traceability events", 16.0, 14.0),
    ("System Settings", "Runtime parameters", 23.0, 14.0),
]

RELATIONS = [
    ("Users", "Roles", "many-to-many"),
    ("Roles", "Permissions", "many-to-many"),
    ("Books", "Authors", "many-to-many"),
    ("Books", "Categories", "many-to-many"),
    ("Books", "Publishers", "many-to-one"),
    ("Loans", "Users", "borrower"),
    ("Loans", "Books", "copy"),
    ("Reservations", "Users", "requester"),
    ("Reservations", "Books", "requested book"),
    ("Fines", "Loans", "generated from"),
    ("Notifications", "Users", "recipient"),
    ("Acquisition Suggestions", "Users", "created by"),
    ("Backups", "System Settings", "configured by"),
    ("Audit Log", "Users", "actor"),
]


def draw_box(c: canvas.Canvas, title: str, subtitle: str, x_cm: float, y_cm: float) -> None:
    x, y = x_cm * cm, y_cm * cm
    w, h = 5.1 * cm, 1.6 * cm
    c.setStrokeColor(colors.HexColor("#334155"))
    c.setFillColor(colors.HexColor("#F8FAFC"))
    c.roundRect(x, y, w, h, 5, fill=1, stroke=1)
    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 9)
    c.drawString(x + 0.25 * cm, y + 1.0 * cm, title)
    c.setFillColor(colors.HexColor("#475569"))
    c.setFont("Helvetica", 7)
    c.drawString(x + 0.25 * cm, y + 0.45 * cm, subtitle)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    c = canvas.Canvas(str(OUTPUT), pagesize=landscape(A4))
    width, height = landscape(A4)
    c.setTitle("SGB-SaaS English Entity Relationship Overview")

    c.setFillColor(colors.HexColor("#0F172A"))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(1.5 * cm, height - 1.5 * cm, "SGB-SaaS Entity Relationship Overview")
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.HexColor("#475569"))
    c.drawString(
        1.5 * cm,
        height - 2.0 * cm,
        "Presentation figure with English aliases; database identifiers remain unchanged in migrations.",
    )

    positions = {title: (x, y) for title, _subtitle, x, y in BOXES}
    centers = {title: ((x + 2.55) * cm, (y + 0.8) * cm) for title, (x, y) in positions.items()}

    c.setStrokeColor(colors.HexColor("#94A3B8"))
    for left, right, label in RELATIONS:
        x1, y1 = centers[left]
        x2, y2 = centers[right]
        c.line(x1, y1, x2, y2)

    for title, subtitle, x, y in BOXES:
        draw_box(c, title, subtitle, x, y)

    c.setFont("Helvetica", 7)
    c.setFillColor(colors.HexColor("#64748B"))
    c.drawRightString(width - 1.5 * cm, 0.8 * cm, "Generated by scripts/generate-english-er-figure.py")
    c.save()


if __name__ == "__main__":
    main()
